# Generated by Django 2.1.7 on 2019-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.EmailField(help_text='required', max_length=200),
        ),
    ]
