# Generated by Django 2.1.7 on 2019-06-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0002_auto_20190615_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='Email_address',
        ),
    ]
