# Generated by Django 2.2.3 on 2019-07-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0003_auto_20190615_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty_level',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('levels', models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('ID1', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(default=True, max_length=200)),
                ('op_1', models.CharField(default=True, max_length=100)),
                ('op_2', models.CharField(default=True, max_length=100)),
                ('op_3', models.CharField(default=True, max_length=100)),
                ('op_4', models.CharField(default=True, max_length=100)),
                ('answer', models.CharField(default=True, max_length=100)),
                ('diff_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='CCA.Difficulty_level')),
                ('field_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='CCA.Field')),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
