# Generated by Django 2.2.3 on 2019-07-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CCA', '0006_auto_20190703_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.IntegerField(max_length=250)),
                ('level2', models.IntegerField(max_length=250)),
                ('level3', models.IntegerField(max_length=250)),
                ('question', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='CCA.Questionaries')),
                ('users', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
