# Generated by Django 2.2.3 on 2019-07-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0007_user_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_marks',
            old_name='level1',
            new_name='Computer',
        ),
        migrations.RenameField(
            model_name='user_marks',
            old_name='level2',
            new_name='English',
        ),
        migrations.RenameField(
            model_name='user_marks',
            old_name='level3',
            new_name='Physics',
        ),
        migrations.RemoveField(
            model_name='user_marks',
            name='question',
        ),
    ]
