# Generated by Django 2.2.3 on 2019-07-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0008_auto_20190716_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_marks',
            name='Computer',
            field=models.IntegerField(default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='user_marks',
            name='English',
            field=models.IntegerField(db_column='ENGLISH', default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='user_marks',
            name='Physics',
            field=models.IntegerField(default='0', max_length=250),
        ),
    ]
