# Generated by Django 2.2.3 on 2019-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCA', '0010_auto_20190717_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_marks',
            name='ACCOUNTING',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_marks',
            name='BIOLOGY',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_marks',
            name='BUSINESS_ADMINISTRATION',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_marks',
            name='CHEMISTRY',
            field=models.IntegerField(default='0'),
        ),
    ]
